version: "3.8"

services:
  notification-db:
    image: postgres:16-alpine
    container_name: labodc-notification-db
    environment:
      POSTGRES_DB: labodc_notification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  notification-service:
    build: .
    container_name: labodc-notification-service
    depends_on:
      - notification-db
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/labodc_notification
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
